import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Check } from "lucide-react";

export const metadata: Metadata = { title: "About", description: "The service standards and approach behind Royal Cleaning Crew in Calgary, Alberta." };

export default function AboutPage() {
  return <>
    <section className="bg-[#222724] text-white"><div className="container grid min-h-[600px] gap-8 py-12 lg:grid-cols-[.9fr_1.1fr] lg:items-stretch lg:py-14">
      <div className="flex flex-col justify-end py-8 lg:py-12"><p className="eyebrow">Royal Cleaning Crew · Calgary</p><h1 className="display mt-5 text-6xl sm:text-7xl lg:text-[86px]">A standard is a way of working.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-white/68">A cleaning service should be clear before the first room and considered through the last detail. That is the standard we want every request to begin with.</p><Link href="/services" className="text-link mt-7 w-fit text-white">Explore the services <ArrowUpRight size={15} /></Link></div>
      <div className="relative min-h-[360px] lg:min-h-[500px]"><Image src="https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1400&q=85" alt="A cleaning professional carefully working in a home" fill sizes="(max-width:1024px) 100vw,52vw" className="object-cover object-center" priority /><span className="absolute bottom-4 left-4 bg-[#1c201d]/80 px-3 py-2 text-[9px] font-bold tracking-[.1em] text-white uppercase">Residential · Calgary</span></div>
    </div></section>
    <section className="py-20 sm:py-24 lg:py-32"><div className="container grid gap-8 lg:grid-cols-[1.1fr_.9fr] lg:gap-16"><h2 className="display max-w-4xl text-5xl sm:text-6xl lg:text-[74px]">Good service starts with knowing what matters in the space.</h2><div className="self-end"><p className="eyebrow">The approach</p><p className="mt-4 text-sm leading-7 text-[var(--muted)]">A lived-in home, a short-term rental and a working office do not share the same rhythm. The useful questions are specific: what is being cleaned, which details matter, how the property is accessed and when the space needs to be ready.</p><p className="mt-4 text-sm leading-7 text-[var(--muted)]">Royal Cleaning Crew is focused on Calgary. Requests are reviewed around location, property condition, service scope and scheduling rather than treated as a one-size-fits-all booking.</p></div></div></section>
    <section className="border-y border-[var(--line)] bg-[#eeece5] py-16 sm:py-20"><div className="container grid gap-9 md:grid-cols-3">{[["01","Clarity before the clean","Service type, access, priorities and optional detail work belong in the conversation before a scope is confirmed."],["02","Care for the setting","Surfaces, routines and property requirements shape how work is planned. Share sensitivities and access notes early."],["03","A deliberate finish","The last pass should account for the areas that make a room feel ready, not only the easiest surfaces to reach."]].map(([number,title,copy])=><article className="border-t border-[#c8c5bb] pt-5" key={number}><span className="display text-4xl text-[var(--brass)]">{number}</span><h2 className="display mt-6 text-3xl sm:text-4xl">{title}</h2><p className="mt-3 max-w-sm text-sm leading-7 text-[var(--muted)]">{copy}</p></article>)}</div></section>
    <section className="py-20 sm:py-24"><div className="container grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">What this means in practice</p><h2 className="display mt-4 text-5xl">No guesswork in the request.</h2></div><ul className="border-t border-[var(--line)]">{["A service-area check before a quote request proceeds","A scope shaped around rooms, condition and selected details","A clear distinction between an inquiry and a confirmed booking","Pricing shown only when approved rates are configured"].map((item)=><li className="flex gap-3 border-b border-[var(--line)] py-5 text-sm leading-6" key={item}><Check className="mt-0.5 shrink-0 text-[var(--brass)]" size={16}/>{item}</li>)}</ul></div></section>
    <section className="bg-[#222724] py-16 text-white sm:py-20"><div className="container flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">A Calgary service</p><h2 className="display mt-4 max-w-2xl text-5xl sm:text-6xl">Tell us what the space needs.</h2></div><Link className="button button-light" href="/contact">Request a Quote <ArrowUpRight size={15}/></Link></div></section>
  </>;
}