import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Check } from "lucide-react";
import { serviceArea } from "@/config/service-area";

export const metadata: Metadata = { title: "Service Areas", description: "Royal Cleaning Crew currently serves Calgary, Alberta. Check your address before requesting a quote." };

const propertyTypes = ["Condos and apartments","Townhomes and detached homes","Offices and workplaces","Short-term rental properties","Move-in and move-out spaces","Newly finished interiors"];

export default function ServiceAreasPage() {
  return <>
    <section className="bg-[#222724] text-white"><div className="container grid min-h-[520px] gap-8 py-10 lg:grid-cols-[.92fr_1.08fr] lg:items-stretch lg:py-12"><div className="flex flex-col justify-end py-7"><p className="eyebrow">Service area · Calgary, Alberta</p><h1 className="display mt-5 text-6xl sm:text-7xl lg:text-[82px]">A local service, with a clear boundary.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-white/65">Royal Cleaning Crew currently accepts service requests within Calgary. The full street address, city, province and postal area are checked together before a request can proceed.</p><Link className="text-link mt-7 w-fit text-white" href="/contact">Check your address <ArrowUpRight size={15}/></Link></div><div className="relative min-h-[300px] lg:min-h-[440px]"><Image src="https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1400&q=85" alt="Urban Calgary streetscape" fill sizes="(max-width:1024px) 100vw,54vw" className="object-cover" priority/><span className="absolute bottom-4 left-4 bg-[#1c201d]/80 px-3 py-2 text-[9px] font-bold tracking-[.1em] text-white uppercase">Calgary, Alberta</span></div></div></section>
    <section className="py-16 sm:py-20 lg:py-24"><div className="container grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Spaces we can review</p><h2 className="display mt-4 text-5xl sm:text-6xl">Different properties. A scope to suit.</h2><p className="mt-5 text-sm leading-7 text-[var(--muted)]">Property type helps shape the request; condition, access and timing help shape the work.</p></div><div className="grid border-l border-t border-[var(--line)] sm:grid-cols-2">{propertyTypes.map((type,index)=><div className="flex min-h-[96px] items-start gap-4 border-b border-r border-[var(--line)] p-5" key={type}><span className="text-[10px] font-bold text-[var(--brass)]">0{index+1}</span><span className="text-sm font-semibold leading-6">{type}</span></div>)}</div></div></section>
    <section className="bg-[#eeece5] py-16 sm:py-20"><div className="container grid gap-8 lg:grid-cols-2"><div><p className="eyebrow">How the location check works</p><h2 className="display mt-4 max-w-xl text-5xl">A Calgary postal prefix is only one part of the check.</h2></div><div className="self-center"><p className="text-sm leading-7 text-[var(--muted)]">The request form checks a Canadian postal-code format against a configurable set of Calgary FSA prefixes, then confirms the city, province and street-address format. A postal code beginning with T alone is not enough.</p><ul className="mt-6 grid gap-3 border-t border-[#c9c6bd] pt-5 text-xs">{["Calgary city","Alberta (AB)","A supported Calgary postal area","A street address with a number"].map((item)=><li className="flex items-center gap-2" key={item}><Check size={14} className="text-[var(--brass)]"/>{item}</li>)}</ul><p className="mt-5 text-xs leading-6 text-[var(--muted)]">Current postal prefixes are maintained in the site’s service-area configuration and can be expanded if service officially adds another community. The current boundary does not include surrounding municipalities.</p></div></div></section>
    <section className="py-16 sm:py-20"><div className="container flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">Current service boundary</p><h2 className="display mt-3 text-4xl">{serviceArea.city}, {serviceArea.province}</h2><p className="mt-3 max-w-xl text-sm leading-7 text-[var(--muted)]">Requests outside Calgary are not accepted by the quote form. A service request is not a confirmed booking; scope and availability are reviewed separately.</p></div><Link href="/pricing" className="button button-dark">Check a service address <ArrowUpRight size={15}/></Link></div></section>
  </>;
}